"""Build the shipped demo case set.

    python -m scanproof.demo

Selects archetype cases from the **test split** using the audit produced by
``scanproof.evaluate``, writes each as a small PNG into ``demo_cases/`` and
caches the full analysis in ``demo_cases/manifest.json``.

Why cache: the recorded demo must never depend on a network call or on GPU
warm-up timing. The cached results are produced by exactly the same
``Analyzer`` the live API uses, and the builder asserts that a fresh live
analysis reproduces the cached verdict before writing — so the cache is
traceable to real computation, not hand-authored.

Licensing: the chest films are PneumoniaMNIST (CC BY 4.0, de-identified,
pediatric, already published by the MedMNIST authors); the ultrasound OOD
probes are BreastMNIST (CC BY 4.0). The phantom is generated by this file.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

import numpy as np
from PIL import Image

from .config import CLASS_NAMES, DEMO_DIR, OOD_PROBE_DATASET, SOURCE_SIZE
from .data import load_split
from .pipeline import Analyzer
from .reliability import BLOCK, PASS, REVIEW


@dataclass
class Archetype:
    slug: str
    title: str
    why: str  # why this case is in the deck — shown in the UI
    pick: object  # (row) -> bool  candidate filter
    rank: object  # (row) -> float  lower is better


def _archetypes() -> list[Archetype]:
    return [
        Archetype(
            "stable-pneumonia",
            "Stable pneumonia call",
            "Confident, and the confidence is earned: nothing in the battery moves it.",
            lambda r: r["verdict"] == PASS and r["correct"] and r["predicted_class"] == "PNEUMONIA",
            lambda r: (r["n_flips"], r["mean_abs_delta"], -r["reliability_score"]),
        ),
        Archetype(
            "stable-normal",
            "Stable normal call",
            "The negative case that also holds up — PASS is not just a high-confidence rubber stamp.",
            lambda r: r["verdict"] == PASS and r["correct"] and r["predicted_class"] == "NORMAL",
            lambda r: (r["n_flips"], r["mean_abs_delta"], -r["reliability_score"]),
        ),
        Archetype(
            "confident-but-fragile",
            "Confident but fragile",
            "High confidence, yet the label collapses under a benign exposure change. "
            "This is the case confidence alone cannot catch.",
            lambda r: r["confidence"] >= 0.85 and r["n_flips"] >= 2,
            lambda r: (-r["confidence"] * r["n_flips"],),
        ),
        Archetype(
            "split-checkpoints",
            "Checkpoints disagree",
            "Three independently trained models, three different answers about the same film.",
            lambda r: not r["unanimous"],
            lambda r: (-r["ensemble_std"],),
        ),
        Archetype(
            "confidently-wrong",
            "Confidently wrong — caught",
            "The model is wrong and sure of it. ScanProof withholds PASS on evidence, "
            "without ever seeing the ground-truth label.",
            lambda r: (not r["correct"]) and r["confidence"] >= 0.80
            and r["verdict"] in (REVIEW, BLOCK),
            lambda r: (-r["confidence"],),
        ),
        Archetype(
            "confidently-wrong-missed",
            "Confidently wrong — missed",
            "An honest failure mode: this error still reaches PASS. Shown so the audit "
            "view's PASS-band accuracy is not mistaken for a guarantee.",
            lambda r: (not r["correct"]) and r["verdict"] == PASS,
            lambda r: (-r["confidence"],),
        ),
        Archetype(
            "borderline",
            "Borderline evidence",
            "Low margin before any perturbation is applied — the model is sitting on the "
            "decision boundary.",
            lambda r: 0.5 <= r["confidence"] <= 0.68,
            lambda r: (r["confidence"],),
        ),
        Archetype(
            "blocked",
            "Blocked on instability",
            "Lowest reliability score in the split: the prediction barely survives contact "
            "with the test battery.",
            lambda r: r["verdict"] == BLOCK,
            lambda r: (r["reliability_score"],),
        ),
    ]


def _phantom() -> np.ndarray:
    """A deterministic synthetic image that is obviously not a chest film.
    Included so the OOD gate can be demonstrated without any external file."""
    rng = np.random.default_rng(20240729)
    yy, xx = np.mgrid[0:SOURCE_SIZE, 0:SOURCE_SIZE].astype(np.float32)
    c = SOURCE_SIZE / 2
    rings = 0.5 + 0.5 * np.sin(np.hypot(xx - c, yy - c) / 6.0)
    grad = xx / SOURCE_SIZE
    img = 0.55 * rings + 0.35 * grad + 0.10 * rng.random((SOURCE_SIZE, SOURCE_SIZE))
    return np.clip(img * 255, 0, 255).astype(np.uint8)


def main() -> None:
    from .config import ARTIFACT_DIR

    cases_path = ARTIFACT_DIR / "audit_cases.json"
    if not cases_path.exists():
        raise SystemExit(
            f"{cases_path} not found — run `python -m scanproof.evaluate` first."
        )
    rows = json.loads(cases_path.read_text())["cases"]
    imgs, labels = load_split("test")

    analyzer = Analyzer()
    manifest: list[dict] = []
    used: set[int] = set()

    def emit(slug, title, why, img, source, true_class, license_note):
        result = analyzer.analyze(img)
        png = f"{slug}.png"
        Image.fromarray(img, mode="L").save(DEMO_DIR / png, optimize=True)
        manifest.append(
            {
                "id": slug,
                "title": title,
                "why_included": why,
                "image": png,
                "source": source,
                "true_class": true_class,
                "license": license_note,
                "cached_result": result.to_dict(),
            }
        )
        print(f"  {slug:<28} {result.verdict:<6} score {result.reliability_score:5.1f}  "
              f"pred {result.predicted_class:<9} truth {true_class}", flush=True)

    for arch in _archetypes():
        pool = [r for r in rows if arch.pick(r) and r["index"] not in used]
        if not pool:
            print(f"  (skipped {arch.slug}: no matching case in the test split)")
            continue
        row = min(pool, key=arch.rank)
        used.add(row["index"])
        i = row["index"]
        emit(
            arch.slug,
            arch.title,
            arch.why,
            imgs[i],
            f"PneumoniaMNIST test split, index {i}",
            CLASS_NAMES[int(labels[i])],
            "CC BY 4.0 — MedMNIST v2 (Yang et al., Sci Data 2023); source images Kermany et al., Cell 2018",
        )

    # --- out-of-distribution probes -------------------------------------
    probe_imgs, _ = load_split("test", flag=OOD_PROBE_DATASET)
    for k, idx in enumerate((3, 41)):
        emit(
            f"ood-ultrasound-{k + 1}",
            "Wrong modality (breast ultrasound)",
            "Not a chest X-ray at all. The classifier still produces a two-class output; "
            "the embedding-distance gate is what refuses it.",
            probe_imgs[idx % len(probe_imgs)],
            f"BreastMNIST test split, index {idx}",
            "n/a — not a chest film",
            "CC BY 4.0 — MedMNIST v2 (Yang et al., Sci Data 2023)",
        )

    emit(
        "ood-phantom",
        "Synthetic phantom",
        "Generated by scanproof/demo.py. Nothing anatomical is present, so any "
        "PNEUMONIA/NORMAL answer is meaningless — the OOD gate should fire.",
        _phantom(),
        "generated by scanproof.demo._phantom()",
        "n/a — synthetic",
        "generated by this repository",
    )

    out = {
        "generated_by": "python -m scanproof.demo",
        "note": (
            "Cached results are produced by the same Analyzer the live API uses. The "
            "pipeline is deterministic, so a live re-analysis reproduces these values."
        ),
        "cases": manifest,
    }
    (DEMO_DIR / "manifest.json").write_text(json.dumps(out, indent=2))
    print(f"\nwrote {len(manifest)} demo cases to {DEMO_DIR}")


if __name__ == "__main__":
    main()
